### ISSUE TITLE
Many Google results for Zammad docs lead to 404 errors

### ISSUE THREAD

**Issue by martinvonwittich** [zammad/zammad-user-documentation#16]
Hi,

we're currently evaluation Zammad and therefore I'm currently googling a lot of Zammad related stuff. Unfortunately, many Google results lead to documentation links that no longer exist. For example the query "zammad working ticket" leads to these results:

1. https://zammad-user-documentation.readthedocs.io/en/latest/working-ticket.html [404]
2. https://zammad-user-documentation.readthedocs.io/en/latest/working-ticket-links.html [404]
3. http://docs.zammad.org/en/latest/general-ticket.html [404]
4. https://github.com/zammad/zammad-user-documentation/blob/master/zammad-ticket-edit.rst [works]
5. https://github.com/zammad/zammad/issues/2068 [works]
6. https://readthedocs.org/projects/zammad-user-documentation-english/downloads/pdf/latest/ [404]
7. (rest are github links)

Would it be possible to add redirects for these URLs that point to the correct links? This would make it a lot less frustrating to search for Zammad documentation :)

**Comment by MrGeneration** [comment]
Hey,

that's not possible, as this is an external service.
We recently changed the documentation and cleaned it up.

What you're searching is mainly this documentation:
https://user-docs.zammad.org/en/latest/  << That's our User-Documentation, all how to work on Zammad as Agent can be found there.

For Administration Stuff (the person who configures Zammad within the Browser), the following documentation might be interesting: https://admin-docs.zammad.org/en/latest/

Sorry for the trouble!

**Comment by martinvonwittich** [comment]
> We recently changed the documentation and cleaned it up.

Yeah, I suspected that might've been the cause :)

> that's not possible, as this is an external service.

Hm, I've never used readthedocs.io personally, but their documentation does describe several kinds of redirects that they seem to support: https://docs.readthedocs.io/en/latest/user-defined-redirects.html
Sounds like those might be useful for this this purpose. I haven't found any information though how to find logs on requests that 404, which might make it pretty hard to identify the URLs that need to be redirected :|

For the time being, I've bookmarked the setup/admin/user docs and will try to use that instead of Google. Hopefully Google will reindex those pages soon :)

**Comment by MrGeneration** [comment]
Okay I hope I managed to find all changes we did in the past 1-2 months.
We have bunches of rewrites inside the documentations now - I did ignore the PDF-File though, hope that's not too much of a bummer. :-)
