### ISSUE TITLE
miss image

### ISSUE THREAD

**Issue by NeverMin** [zammad/zammad-user-documentation#2]
zammad-user-documentation/zammad-ticket-edit.rst:80: WARNING: image file not readable: images/gettingstarted/zammad-ticket-edit--Ticket-Settings.jpg

**Comment by MrGeneration** [comment]
Hey,

thanks for sharing.
With commit https://github.com/zammad/zammad-user-documentation/commit/de616a2b43522aa2f03cec67bdd9383b3930ff98#diff-1967cf183b651207fcd8a7c3898424ac the image has been removed from the user documentation and got moved to admin documentation :)

**Comment by MrGeneration** [comment]
@KoJie could you please close this? I think it's fixed. :)
