### ISSUE TITLE
wrong search strings

### ISSUE THREAD

**Issue by KoJie** [zammad/zammad-user-documentation#30]
https://user-docs.zammad.org/en/latest/advanced/search.html

the first search-string example "customer: some name" is not working. Nothing is found when searching for this string. It needs to be e.g.:
customer.firstname: John
customer.lastname: Doe

**Comment by MrGeneration** [comment]
I cannot reproduce the described error.
I've verified this on a current Zammad instance and the search strings are working as expected.

If you believe this is a mistake, please provide *a lot* more context so that I can understand the issue better.
