### ISSUE TITLE
Rework keyboard shortcuts according to changes in Zammad

### ISSUE THREAD

**Issue by ralf401** [zammad/zammad-user-documentation#313]

**Comment by dvuckovic** [comment]
@ralf401 Just a couple of points that I may have missed to communicate so far:

- The new shortcut layout is not analogous to the old one, meaning it's not just about the modifiers: even some shortcut keys are different now.
- Disabling of keyboard shortcuts and switching to the old layout will persist for the current browser only. It is not saved in user preferences ATM.
- There was a "fix" to also rename "alt" key to "option" on MacOS, but perhaps this is not relevant for the docs.
- Finally, the new shortcut layout is the new default, so the users will have to switch explicitly to the old layout if they so desire.
