### ISSUE TITLE
New languages

### ISSUE THREAD

**Issue by rmundel** [zammad/zammad-user-documentation#4]
Hey there!
I'm looking forward to translate the user documentation to brazilian portuguese, can someone point me in the right direction on how to do it?
I intend on sharing with the community once it is complete of course.

**Comment by rmundel** [comment]
Dang it! I just read the README file... Gonna try that. Sorry to bother.

**Comment by hanneshal** [comment]
Hi @rmundel ,

thank you for your support. We are switching the base language soon to english. Right now it's based on german and so are the language files. Is it OK for you that I give you an info when we updated the translation? If you would start the translation right now your work woud, probably, be partly lost.

regards

Johannes

**Comment by rmundel** [comment]
Hey @hanneshal ! Thanks on the followup, I'm glad you commented lol
I'll wait the language update then.
Could you guys consider using a colaborative tool to help ease the translations process? (like Zanata, Crowdin, Pootle, etc).

**Comment by hanneshal** [comment]
We use http://transifex.com for this right now. It's free for open source and we are able to use our command line tools for the processing of new strings. Thats also one reason why we switch the base language to english.   To have a clean state for everyone.

**Comment by MrGeneration** [comment]
pt_BR is now available for translation!

https://www.transifex.com/zammad/zammad-user-documentation/language/pt_BR/

If you need help, let us know.
