### ISSUE TITLE
German translation: "Text Bausteine" is not correct

### ISSUE THREAD

**Issue by yogo1212** [zammad/zammad-user-documentation#48]
It's "Textbausteine". Same goes for the main software.

I would love to send a PR but with transifex it is just not worth the time.
It's not even possible to grep for that string in order to check in which repo contains it for the web application....

`s/Text Baustein/Textbaustein/g`

**Comment by MrGeneration** [comment]
Sorry we're having translations on transifex.
Closing the issue due out of scope of this repo.
