### ISSUE TITLE
Can I add Chinese translation to the user manual

### ISSUE THREAD

**Issue by NeverMin** [zammad/zammad-user-documentation#64]
@mgruner , Can I add Chinese (zh_CN) translation to the user manual in [Weblate](https://translations.zammad.org/projects/documentations/user-documentation/)? Let me merge my [previous translations](https://github.com/zammadcn/zammad-documentation), thanks.

**Comment by MrGeneration** [comment]
My bad thank you. It wouldn't find it.
Chinese language is now activated for weblate ( https://translations.zammad.org/projects/documentations/user-documentation/zh_Hans/ )

Thank you for your contribution!
